### PR TITLE
Code coverage

### PR DESCRIPTION
**Pull request by Zsupi**
# Done:

- #14 Issue task 3
- Added documentation for SonarCloud.
- made dotnet.yml workflow callable
- merge two workflows _(call dotnet.yml from SonarCloud build.yml)_

### CODE REVIEW

**Review by BitaiBence — APPROVED** [review]
Approve

**Review by MokosZalan — APPROVED** [review]
Looks good

**Review by adamooo1 — APPROVED** [review]
Everything OK!

**Review by JanosVargaBME — APPROVED** [review]
Looks good to me, would recommend 10/10

**Pull request merged**
